remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
author: Natalia Edelson
title: Data Science Projects 
header-img: img/home-bg.png
email: nataliagoncharov@gmail.com
copyright_name: Natalia Edelson
description: > # this means to ignore newlines until "baseurl:"
  “That which cannot be measured cannot be proven.” - Anthony Richardson
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  NataliaEde
permalink: pretty
paginate: 5


